services:
  mysql:
    image: mysql:8.3
    container_name: system-param-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: system_param
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 30
